export const ADMIN_ROUTE = '/admin';
export const LOGIN_ROUTE = '/login';
export const REGISTRATION_ROUTE = '/registration';
export const SHOP_ROUTE = '/';
export const BASKET_ROUTE = '/basket'; 
export const DEVICE_ROUTE = '/device';
// export const AUTH_ROUTE = '/auth';
// export const ADMIN = 'ADMIN';
// export const USER = 'USER';